### ISSUE TITLE
Units are incorrect for V.Qp and V.Qs

### ISSUE THREAD

**Issue by frank-engel-usgs** [frank-engel-usgs/VMT#15]
WMA forum user ddileona mentioned a units issue in the computation of secondary flow discharge (zsd) as reported in the variable V.Qp in [this forum post](https://simon.er.usgs.gov/smf/index.php?topic=1383.0). 

The proposed solution is to correct the units conversion in lines 23 & 24 so that the resultant computation is in m^2/s. 

The main comment is reproduced here:
> Hi Frank,
> 
> The mean flow direction of the MCS (V.mfd) for an example transect in our data set is 173.2 deg. The angle of the MCS (V.theta) is 89.3 deg. Are those the proper angles to consider?
> 
> If I calculate the discharge through each bin in m^3/s:
> 
>            Qbins = V.u/100*V.binWidth*V.binHeight,         where V.u is streamwise velocities for the MCS, originally in cm/s
> 
> And then sum those values:
> 
>            Q = nansum(nansum(Qbins))
> 
> I get something the correct order of magnitude, and very close to the WinRiver II measured discharge (so not including the top, bottom, and edge estimates). 
> 
> If I do the same calculation, but don't convert the velocity into m/s
> 
>           Qbins = V.u*V.binWidth*V.binHeight
>           Q = nansum(nansum(Qbins))
> 
> I get something the same order of magnitude and very close to V.Qp.
> 
> This made me think that there is an un-converted cm unit in the computation of V.Qp. And if you go into the code of VMT_CompMeanXS_PreSec.m you find
> 
>  V.Qp=nansum(nansum(qpi));%cm*m^2/s   on line 47.

**Comment by frank-engel** [comment]
The revised version now addresses the units inconsistency, and reports a couple of new useful quantities in the log window:
![image](https://user-images.githubusercontent.com/7658425/46826730-5b76d580-cd5c-11e8-8871-b04a35136ed2.png)

Closing this issue.
