### ISSUE TITLE
Issue with MCS Normal Vector 

### ISSUE THREAD

**Issue by Ryan-Jackson-USGS** [frank-engel-usgs/VMT#5]
There are two issues with the MCS normal vector reported in the VMT shiptrack plot in VMT 4.08 (r20170404).

1. The mean flow direction vector and the MCS normal vector appear to be reversed. According to the user manual, the red vector is the normal vector and the black vector is the mean flow direction. 
![image](https://cloud.githubusercontent.com/assets/28065460/25452588/ba7c6eca-2a8b-11e7-9e38-5daa66358453.png)

However, the VMT_PlotShiptracks.m source code shows the red vector is the mean flow direction and the black vector is the normal vector.
![image](https://cloud.githubusercontent.com/assets/28065460/25452677/03f9372c-2a8c-11e7-9de9-4bef6c10cda0.png)

2. In some cases, the normal vector to the MCS (black vector) is not plotted correctly or is incorrectly computed for the MCS. For example, here is a shiptrack plot from the Wabash cutoff dataset (01/07/09, transects 24-28; quad3) where the black normal vector is clearly incorrectly plotted. The log window shows the normal (streamwise) direction to be 231.7 deg which appears correct and is close to the primary flow direction, so I believe the issue is with the VMT_PlotShiptracks.m plotting function which recomputes the normal vector rather than using  V.phi.
![image](https://cloud.githubusercontent.com/assets/28065460/25453072/64842d1c-2a8d-11e7-9dca-bde2b048578c.png)

**Comment by frank-engel-usgs** [comment]
@Ryan-Jackson-USGS I have resolved this issue. Thanks for pointing it out!
