### ISSUE TITLE
Excel Output: MCS missing bin depths and smoothed data (v,w) include scaling

### ISSUE THREAD

**Issue by Ryan-Jackson-USGS** [frank-engel-usgs/VMT#6]
There are two issues with the VMT 4.08 r20170404 Excel output tables:

1. The MeanCrossSection worksheet is missing the bin (or grid node) depths. Only the bed elevation is listed. 
![image](https://cloud.githubusercontent.com/assets/28065460/25453513/d7d58ae4-2a8e-11e7-8651-3db824db36d6.png)

2. The transverse velocity and vertical velocity components listed in the Smoothed_MeanCrossSection worksheet are incorrect. The transverse velocity must be multiplied by the vector scale factor and the sign must be changed (if the cross section is flipped to look DS) to recover the true transverse velocity (as given if one sets the contour variable to be the transverse velocity and exports the Excel file--see figure below). Likewise, the vertical velocity in this worksheet must be divided by (sf/exag) and the sign must be flipped if the reference is DFS to recover the true vertical velocity (sf is the vector scale factor and exag is the vertical exaggeration). 
![image](https://cloud.githubusercontent.com/assets/28065460/25453808/eb09aa7c-2a8f-11e7-831f-4b9063991f2e.png)

**Comment by frank-engel-usgs** [comment]
I have modified VMT to address these issues. VMT now outputs a formatted Excel file, and implements the suggestions @Ryan-Jackson-USGS  has made. 

The new release v4.08 r20171005 will be compiled and distributed on the OSW VMT website.
